name: Example workflow for Node using Snyk
on: push
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=high --json-file-output=results.json
      - name: Count number of resulting vulnerabilities
        run: |
          echo "VULNS=$(cat results.json | jq '.vulnerabilities | map(select(.malicious == true)) | length')" >> $GITHUB_ENV
      - name: Fail if mailicious vulns are found
        if: env.VULNS > 0
        run: |
          exit 1
